# !/bin/bash
set -e
export ZONE=us-central1-a
export DOCKER_IMAGE_BASE_NAME=appweb
export KUBERNETES_CLUSTER_NAME_SUFFIX=kb-cluster
echo "SET ZONE=${ZONE}"
echo "SET DOCKER_IMAGE_BASE_NAME=${DOCKER_IMAGE_BASE_NAME}"
echo "SET KUBERNETES_CLUSTER_NAME_SUFFIX=${KUBERNETES_CLUSTER_NAME_SUFFIX}"
