version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
          - staging
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/workspace
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install node packages
          command: |
            docker build -t appweb .

      - run:
          name: Run tests
          command: |
            docker run --rm --entrypoint '/bin/sh' appweb:latest -c 'npm test'
            
      - run:
          name: Build and Deploy
          command: |
            sh ./deployment.sh

